const colors = [
  { name: "Light Yellow", color: "#FFFFCC" },
  { name: "Light Green", color: "#CCFFCC" },
  { name: "Light Blue", color: "#CCFFFF" },
  { name: "Light Pink", color: "#FFCCFF" },
  { name: "Light Purple", color: "#E6CCFF" },
  { name: "Light Red", color: "#FFCCCC" },
  { name: "Light Gray", color: "#F0F0F0" },
  { name: "Light Lavender", color: "#E6E6FA" },
  { name: "Light Peach", color: "#FFD8B1" },
  { name: "Light Mint", color: "#98FB98" },
  { name: "Light Salmon", color: "#FFA07A" },
  { name: "Light Gold", color: "#FFD700" },
  { name: "Light Orchid", color: "#E6A8D7" },
  { name: "Light Coral", color: "#F08080" },
  { name: "Light Sky Blue", color: "#87CEFA" },
  { name: "Light Beige", color: "#F5F5DC" },
  { name: "Light Slate Gray", color: "#778899" },
  { name: "Light Violet", color: "#D8BFD8" },
  { name: "Light Olive", color: "#C0FFC0" },
  { name: "Light Sea Green", color: "#20B2AA" },
  { name: "Light Magenta", color: "#FF77FF" },
  { name: "Light Khaki", color: "#F0E68C" },
  { name: "Light Teal", color: "#ADD8E6" },
  { name: "Light Tan", color: "#D2B48C" },
  { name: "Light Slate Blue", color: "#8470FF" },
  { name: "Light Chocolate", color: "#D2691E" },
];

export default colors;
